require: rubocop-rspec

AllCops:
  NewCops: enable

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/SubjectStub:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - spec/spec_helper.rb
    - spec/account_spec.rb
    - spec/base_card_spec.rb
    - spec/capitalist_card_spec.rb
    - spec/console_spec.rb
    - spec/usual_card_spec.rb
    - spec/virtual_card_spec.rb
